### ISSUE TITLE
Can this plagin support gradio > 5.0?

### ISSUE THREAD

**Issue by anyshu** [edgarGracia/gradio_image_annotator#15]
Hi, Dear,
right now gradio is updated to 5.4.0, do you have plan to support > 5.0?

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio-image-annotation 0.2.4 requires gradio<5.0,>=4.29, but you have gradio 5.4.0 which is incompatible.
gradio-image-annotator 0.0.1 requires gradio<5.0,>=4.0, but you have gradio 5.4.0 which is incompatible.

**Comment by edgarGracia** [comment]
Hi, the component is already compatible with the new version but we had to update the project dependencies, the new release should work (`gradio-image-annotation==0.2.5`).
Thanks for pointing this out!
