### ISSUE TITLE
Cannot upload image. 

### ISSUE THREAD

**Issue by SRagy** [edgarGracia/gradio_image_annotator#2]
It gets stuck forever uploading an image, not sure if this relates to the payload processing somehow, but even in your example, if you close the provided image and then attempt to upload a new one, then it gets stuck. It would be nice to be able to upload an image and then draw the boxes.

**Comment by edgarGracia** [comment]
Hi, it seems like newer versions of Gradio have introduced some changes that break the image uploading.
I will take a look, but in the meantime ``gradio<=4.28`` seems to work well.

**Comment by SRagy** [comment]
Thanks a lot for the workaround. Reverting to an earlier gradio does seem to have fixed it.
